### ISSUE TITLE
Clear All Completed Button is disabled after removing a task

### ISSUE THREAD

**Issue by jsug9** [Tadesse-Alemayehu/To-Do-list#8]
When a task is removed, the Clear All Button is disabled, apparently due to an issue with the indices.

**Comment by Tadesse-Alemayehu** [comment]
Thanks for the reprt. the issue hase been fixed with

**Comment by TadesseDev** [comment]
Thanks for the report. the issue has been fixed with https://github.com/Tadesse-Alemayehu/To-Do-list/commit/149a5ba894eb5a265bac906ac33ab33c1ad124af commit hash.
